#[derive(Clone, Debug)]
pub struct AppItem {
    pub name: String,
    pub name_lc: String,
    pub description: String,
    pub description_lc: String,
    pub category: AppCategory,
    pub group: String,
    pub group_lc: String,
    pub package_name: String,
    pub package_name_lc: String,
    pub package_names: Vec<String>,
    pub package_names_lc: Vec<String>,
    pub can_reinstall: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AppCategory {
    WindowsApps,
    Capabilities,
    OptionalFeatures,
}

pub fn get_all_apps() -> Vec<AppItem> {
    let mut apps = Vec::new();
    apps.extend(get_windows_apps());
    apps.extend(get_capabilities());
    apps.extend(get_optional_features());
    apps
}

#[allow(clippy::too_many_arguments)]
fn app_item(
    _id: &str,
    name: &str,
    description: &str,
    category: AppCategory,
    group: &str,
    package_name: &str,
    _package_names: Vec<&str>,
    _capability_name: &str,
    _optional_feature_name: &str,
    can_reinstall: bool,
    _requires_reboot: bool,
    _ms_store_id: &str,
) -> AppItem {
    let package_names: Vec<String> = _package_names.into_iter().map(str::to_string).collect();
    let package_names_lc: Vec<String> = package_names
        .iter()
        .map(|s| s.to_ascii_lowercase())
        .collect();
    AppItem {
        name: name.to_string(),
        name_lc: name.to_ascii_lowercase(),
        description: description.to_string(),
        description_lc: description.to_ascii_lowercase(),
        category,
        group: group.to_string(),
        group_lc: group.to_ascii_lowercase(),
        package_name: package_name.to_string(),
        package_name_lc: package_name.to_ascii_lowercase(),
        package_names,
        package_names_lc,
        can_reinstall,
    }
}

fn get_windows_apps() -> Vec<AppItem> {
    vec![
        app_item(
            "windows-app-3d-viewer",
            "3D Viewer",
            "View 3D models and animations",
            AppCategory::WindowsApps,
            "3D/Mixed Reality",
            "Microsoft.Microsoft3DViewer",
            vec!["Microsoft.Microsoft3DViewer"],
            "",
            "",
            true,
            false,
            "9NBLGGH42THS",
        ),
        app_item(
            "windows-app-mixed-reality-portal",
            "Mixed Reality Portal",
            "Portal for Windows Mixed Reality experiences",
            AppCategory::WindowsApps,
            "3D/Mixed Reality",
            "Microsoft.MixedReality.Portal",
            vec!["Microsoft.MixedReality.Portal"],
            "",
            "",
            true,
            false,
            "9NG1H8B3ZC7M",
        ),
        app_item(
            "windows-app-bing-search",
            "Bing Search",
            "Bing search integration for Windows",
            AppCategory::WindowsApps,
            "Bing/Search",
            "Microsoft.BingSearch",
            vec!["Microsoft.BingSearch"],
            "",
            "",
            true,
            false,
            "9NZBF4GT040C",
        ),
        app_item(
            "windows-app-microsoft-news",
            "Microsoft News",
            "Microsoft News app",
            AppCategory::WindowsApps,
            "Bing/Search",
            "Microsoft.BingNews",
            vec!["Microsoft.BingNews"],
            "",
            "",
            true,
            false,
            "9WZDNCRFHVFW",
        ),
        app_item(
            "windows-app-msn-weather",
            "MSN Weather",
            "Weather forecasts and information",
            AppCategory::WindowsApps,
            "Bing/Search",
            "Microsoft.BingWeather",
            vec!["Microsoft.BingWeather"],
            "",
            "",
            true,
            false,
            "9WZDNCRFJ3Q2",
        ),
        app_item(
            "windows-app-camera",
            "Camera",
            "Windows Camera app",
            AppCategory::WindowsApps,
            "Camera/Media",
            "Microsoft.WindowsCamera",
            vec!["Microsoft.WindowsCamera"],
            "",
            "",
            true,
            false,
            "9WZDNCRFJBBG",
        ),
        app_item(
            "windows-app-clipchamp",
            "Clipchamp",
            "Video editor app",
            AppCategory::WindowsApps,
            "Camera/Media",
            "Clipchamp.Clipchamp",
            vec!["Clipchamp.Clipchamp"],
            "",
            "",
            true,
            false,
            "9P1J8S7CCWWT",
        ),
        app_item(
            "windows-app-alarms-clock",
            "Alarms & Clock",
            "Clock, alarms, timer, and stopwatch app",
            AppCategory::WindowsApps,
            "System Utilities",
            "Microsoft.WindowsAlarms",
            vec!["Microsoft.WindowsAlarms"],
            "",
            "",
            true,
            false,
            "9WZDNCRFJ3PR",
        ),
        app_item(
            "windows-app-cortana",
            "Cortana",
            "Microsoft's virtual assistant",
            AppCategory::WindowsApps,
            "System Utilities",
            "Microsoft.549981C3F5F10",
            vec!["Microsoft.549981C3F5F10"],
            "",
            "",
            false,
            false,
            "9NFFX4SZZ23L",
        ),
        app_item(
            "windows-app-get-help",
            "Get Help",
            "Microsoft support app",
            AppCategory::WindowsApps,
            "System Utilities",
            "Microsoft.GetHelp",
            vec!["Microsoft.GetHelp"],
            "",
            "",
            true,
            false,
            "9PKDZBMV1H3T",
        ),
        app_item(
            "windows-app-calculator",
            "Calculator",
            "Calculator app with standard, scientific, and programmer modes",
            AppCategory::WindowsApps,
            "System Utilities",
            "Microsoft.WindowsCalculator",
            vec!["Microsoft.WindowsCalculator"],
            "",
            "",
            true,
            false,
            "9WZDNCRFHVN5",
        ),
        app_item(
            "windows-app-dev-home",
            "Dev Home",
            "Development environment for Windows",
            AppCategory::WindowsApps,
            "Development",
            "Microsoft.Windows.DevHome",
            vec!["Microsoft.Windows.DevHome"],
            "",
            "",
            true,
            false,
            "9N8MHTPHNGVV",
        ),
        app_item(
            "windows-app-family-safety",
            "Microsoft Family Safety",
            "Family safety and screen time management",
            AppCategory::WindowsApps,
            "Communication",
            "MicrosoftCorporationII.MicrosoftFamily",
            vec!["MicrosoftCorporationII.MicrosoftFamily"],
            "",
            "",
            true,
            false,
            "9PDJDJS743XF",
        ),
        app_item(
            "windows-app-mail-calendar",
            "Mail and Calendar",
            "Microsoft Mail and Calendar apps",
            AppCategory::WindowsApps,
            "Communication",
            "microsoft.windowscommunicationsapps",
            vec!["microsoft.windowscommunicationsapps"],
            "",
            "",
            true,
            false,
            "9WZDNCRFHVQM",
        ),
        app_item(
            "windows-app-skype",
            "Skype",
            "Video calling and messaging app",
            AppCategory::WindowsApps,
            "Communication",
            "Microsoft.SkypeApp",
            vec!["Microsoft.SkypeApp"],
            "",
            "",
            false,
            false,
            "9WZDNCRFJ364",
        ),
        app_item(
            "windows-app-teams",
            "Microsoft Teams",
            "Team collaboration and communication app",
            AppCategory::WindowsApps,
            "Communication",
            "MSTeams",
            vec!["MSTeams", "MicrosoftTeams"],
            "",
            "",
            true,
            false,
            "XP8BT8DW290MPQ",
        ),
        app_item(
            "windows-app-feedback-hub",
            "Feedback Hub",
            "App for sending feedback to Microsoft",
            AppCategory::WindowsApps,
            "System Tools",
            "Microsoft.WindowsFeedbackHub",
            vec!["Microsoft.WindowsFeedbackHub"],
            "",
            "",
            true,
            false,
            "9NBLGGH4R32N",
        ),
        app_item(
            "windows-app-maps",
            "Maps",
            "Microsoft Maps app",
            AppCategory::WindowsApps,
            "System Tools",
            "Microsoft.WindowsMaps",
            vec!["Microsoft.WindowsMaps"],
            "",
            "",
            true,
            false,
            "9WZDNCRDTBVB",
        ),
        app_item(
            "windows-app-terminal",
            "Terminal",
            "Modern terminal application for Windows",
            AppCategory::WindowsApps,
            "System Tools",
            "Microsoft.WindowsTerminal",
            vec!["Microsoft.WindowsTerminal"],
            "",
            "",
            true,
            false,
            "9N0DX20HK701",
        ),
        app_item(
            "windows-app-office-hub",
            "MS 365 Copilot (Office Hub)",
            "Microsoft 365 Copilot (formerly known as Office hub)",
            AppCategory::WindowsApps,
            "Office",
            "Microsoft.MicrosoftOfficeHub",
            vec!["Microsoft.MicrosoftOfficeHub"],
            "",
            "",
            true,
            false,
            "9WZDNCRD29V9",
        ),
        app_item(
            "windows-app-outlook",
            "Outlook for Windows",
            "Reimagined Outlook app for Windows",
            AppCategory::WindowsApps,
            "Office",
            "Microsoft.OutlookForWindows",
            vec!["Microsoft.OutlookForWindows"],
            "",
            "",
            true,
            false,
            "9NRX63209R7B",
        ),
        app_item(
            "windows-app-paint-3d",
            "Paint 3D",
            "3D modeling and editing app",
            AppCategory::WindowsApps,
            "Graphics",
            "Microsoft.MSPaint",
            vec!["Microsoft.MSPaint"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-paint",
            "Paint",
            "Traditional image editing app",
            AppCategory::WindowsApps,
            "Graphics",
            "Microsoft.Paint",
            vec!["Microsoft.Paint"],
            "",
            "",
            true,
            false,
            "9PCFS5B6T72H",
        ),
        app_item(
            "windows-app-photos",
            "Photos",
            "Photo viewing and editing app",
            AppCategory::WindowsApps,
            "Graphics",
            "Microsoft.Windows.Photos",
            vec!["Microsoft.Windows.Photos"],
            "",
            "",
            true,
            false,
            "9WZDNCRFJBH4",
        ),
        app_item(
            "windows-app-snipping-tool",
            "Snipping Tool",
            "Screen capture and annotation tool",
            AppCategory::WindowsApps,
            "Graphics",
            "Microsoft.ScreenSketch",
            vec!["Microsoft.ScreenSketch"],
            "",
            "",
            true,
            false,
            "9MZ95KL8MR0L",
        ),
        app_item(
            "windows-app-people",
            "People",
            "Contact management app",
            AppCategory::WindowsApps,
            "Social",
            "Microsoft.People",
            vec!["Microsoft.People"],
            "",
            "",
            true,
            false,
            "9NBLGGH10PG8",
        ),
        app_item(
            "windows-app-power-automate",
            "Power Automate",
            "Desktop automation tool",
            AppCategory::WindowsApps,
            "Automation",
            "Microsoft.PowerAutomateDesktop",
            vec!["Microsoft.PowerAutomateDesktop"],
            "",
            "",
            true,
            false,
            "9NFTCH6J7FHV",
        ),
        app_item(
            "windows-app-quick-assist",
            "Quick Assist",
            "Remote assistance tool",
            AppCategory::WindowsApps,
            "Support",
            "MicrosoftCorporationII.QuickAssist",
            vec!["MicrosoftCorporationII.QuickAssist"],
            "",
            "",
            true,
            false,
            "9P7BP5VNWKX5",
        ),
        app_item(
            "windows-app-solitaire",
            "Solitaire Collection",
            "Microsoft Solitaire Collection games",
            AppCategory::WindowsApps,
            "Games",
            "Microsoft.MicrosoftSolitaireCollection",
            vec!["Microsoft.MicrosoftSolitaireCollection"],
            "",
            "",
            true,
            false,
            "9WZDNCRFHWD2",
        ),
        app_item(
            "windows-app-xbox",
            "Xbox",
            "Xbox App for Windows",
            AppCategory::WindowsApps,
            "Games",
            "Microsoft.GamingApp",
            vec!["Microsoft.GamingApp", "Microsoft.XboxApp"],
            "",
            "",
            true,
            false,
            "9MV0B5HZVK9Z",
        ),
        app_item(
            "windows-app-xbox-identity-provider",
            "Xbox Identity Provider",
            "Authentication service for Xbox Live and related Microsoft gaming services",
            AppCategory::WindowsApps,
            "Games",
            "Microsoft.XboxIdentityProvider",
            vec!["Microsoft.XboxIdentityProvider"],
            "",
            "",
            true,
            false,
            "9WZDNCRD1HKW",
        ),
        app_item(
            "windows-app-xbox-game-bar-plugin",
            "Xbox Game Bar Plugin",
            "Extension component for Xbox Game Bar providing additional functionality",
            AppCategory::WindowsApps,
            "Games",
            "Microsoft.XboxGameOverlay",
            vec!["Microsoft.XboxGameOverlay"],
            "",
            "",
            true,
            false,
            "9NBLGGH537C2",
        ),
        app_item(
            "windows-app-xbox-live-ingame",
            "Xbox Live In-Game Experience",
            "Core component for Xbox Live services within games",
            AppCategory::WindowsApps,
            "Games",
            "Microsoft.Xbox.TCUI",
            vec!["Microsoft.Xbox.TCUI"],
            "",
            "",
            true,
            false,
            "9NKNC0LD5NN6",
        ),
        app_item(
            "windows-app-xbox-game-bar",
            "Xbox Game Bar",
            "Gaming overlay with screen capture, performance monitoring, and social features",
            AppCategory::WindowsApps,
            "Games",
            "Microsoft.XboxGamingOverlay",
            vec!["Microsoft.XboxGamingOverlay"],
            "",
            "",
            true,
            false,
            "9NZKPSTSNW4P",
        ),
        app_item(
            "windows-app-store",
            "Microsoft Store",
            "App store for Windows",
            AppCategory::WindowsApps,
            "Store",
            "Microsoft.WindowsStore",
            vec!["Microsoft.WindowsStore"],
            "",
            "",
            true,
            false,
            "9WZDNCRFJBMP",
        ),
        app_item(
            "windows-app-media-player",
            "Media Player",
            "Music player app",
            AppCategory::WindowsApps,
            "Media",
            "Microsoft.ZuneMusic",
            vec!["Microsoft.ZuneMusic"],
            "",
            "",
            true,
            false,
            "9WZDNCRFJ3PT",
        ),
        app_item(
            "windows-app-movies-tv",
            "Movies & TV",
            "Video player app",
            AppCategory::WindowsApps,
            "Media",
            "Microsoft.ZuneVideo",
            vec!["Microsoft.ZuneVideo"],
            "",
            "",
            true,
            false,
            "9WZDNCRFJ3P2",
        ),
        app_item(
            "windows-app-sound-recorder",
            "Sound Recorder",
            "Audio recording app",
            AppCategory::WindowsApps,
            "Media",
            "Microsoft.WindowsSoundRecorder",
            vec!["Microsoft.WindowsSoundRecorder"],
            "",
            "",
            true,
            false,
            "9WZDNCRFHWKN",
        ),
        app_item(
            "windows-app-sticky-notes",
            "Sticky Notes",
            "Note-taking app",
            AppCategory::WindowsApps,
            "Productivity",
            "Microsoft.MicrosoftStickyNotes",
            vec!["Microsoft.MicrosoftStickyNotes"],
            "",
            "",
            true,
            false,
            "9NBLGGH4QGHW",
        ),
        app_item(
            "windows-app-tips",
            "Tips",
            "Windows tutorial app",
            AppCategory::WindowsApps,
            "Productivity",
            "Microsoft.Getstarted",
            vec!["Microsoft.Getstarted"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-todo",
            "To Do: Lists, Tasks & Reminders",
            "Task management app",
            AppCategory::WindowsApps,
            "Productivity",
            "Microsoft.Todos",
            vec!["Microsoft.Todos"],
            "",
            "",
            true,
            false,
            "9NBLGGH5R558",
        ),
        app_item(
            "windows-app-notepad",
            "Notepad",
            "Text editing app",
            AppCategory::WindowsApps,
            "Productivity",
            "Microsoft.WindowsNotepad",
            vec!["Microsoft.WindowsNotepad"],
            "",
            "",
            true,
            false,
            "9MSMLRH6LZF3",
        ),
        app_item(
            "windows-app-phone-link",
            "Phone Link",
            "Connect your Android or iOS device to Windows",
            AppCategory::WindowsApps,
            "Phone",
            "Microsoft.YourPhone",
            vec!["Microsoft.YourPhone"],
            "",
            "",
            true,
            false,
            "9NMPJ99VJBWV",
        ),
        app_item(
            "windows-app-copilot",
            "Copilot",
            "AI assistant for Windows, includes Copilot provider and Store components",
            AppCategory::WindowsApps,
            "AI",
            "Microsoft.Copilot",
            vec![
                "Microsoft.Copilot",
                "Microsoft.Windows.Ai.Copilot.Provider",
                "Microsoft.Copilot_8wekyb3d8bbwe",
            ],
            "",
            "",
            true,
            false,
            "9NHT9RB2F4HD",
        ),
        app_item(
            "windows-app-client-aix",
            "Windows AI Experience",
            "Core Windows AI experience package (MicrosoftWindows.Client.AIX)",
            AppCategory::WindowsApps,
            "AI",
            "MicrosoftWindows.Client.AIX",
            vec!["MicrosoftWindows.Client.AIX"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-client-copilot",
            "Windows Copilot Client",
            "System Copilot client package (MicrosoftWindows.Client.CoPilot)",
            AppCategory::WindowsApps,
            "AI",
            "MicrosoftWindows.Client.CoPilot",
            vec!["MicrosoftWindows.Client.CoPilot"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-edge-game-assist",
            "Edge Game Assist",
            "Edge Game Assist AI overlay for gaming",
            AppCategory::WindowsApps,
            "AI",
            "Microsoft.Edge.GameAssist",
            vec!["Microsoft.Edge.GameAssist"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-office-actions-server",
            "Office Actions Server",
            "Office AI Actions Server for automated AI-powered actions",
            AppCategory::WindowsApps,
            "AI",
            "Microsoft.Office.ActionsServer",
            vec!["Microsoft.Office.ActionsServer"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-ai-manager",
            "AI Manager",
            "Office AI Manager (aimgr) for managing AI services",
            AppCategory::WindowsApps,
            "AI",
            "aimgr",
            vec!["aimgr"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-writing-assistant",
            "Writing Assistant",
            "Microsoft Office Writing Assistant AI tool",
            AppCategory::WindowsApps,
            "AI",
            "Microsoft.WritingAssistant",
            vec!["Microsoft.WritingAssistant"],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-ai-workloads",
            "AI Workload Packages",
            "Windows AI workload packages including ONNX Runtime, Semantic Text, Image Search, Content Extraction, Screen Region Detection, Text Recognition, and Image Content Moderation",
            AppCategory::WindowsApps,
            "AI",
            "WindowsWorkload.OnnxRuntimeGenAI",
            vec![
                "WindowsWorkload.OnnxRuntimeGenAI",
                "WindowsWorkload.SemanticTextSimilarity",
                "WindowsWorkload.ImageSearch",
                "WindowsWorkload.ContentExtraction",
                "WindowsWorkload.ScreenRegionDetection",
                "WindowsWorkload.TextRecognition",
                "WindowsWorkload.ImageContentModeration",
                "WindowsWorkload.ScreenSemanticsOCR",
                "WindowsWorkload.ImageSuperResolution",
                "WindowsWorkload.ObjectErase",
                "WindowsWorkload.ImageDescriptor",
                "WindowsWorkload.PortraitBlur",
                "WindowsWorkload.TextToSpeech",
                "WindowsWorkload.SpeechToText",
                "WindowsWorkload.ImageSegmentation",
                "WindowsWorkload.CreativeFilter",
                "WindowsWorkload.StudioEffects",
                "WindowsWorkload.SubtitleTranslation",
                "WindowsWorkload.Summarization",
                "WindowsWorkload.RewriteTextSuggestion",
            ],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-copilot-plus-pc",
            "Copilot+ PC AI Packages",
            "AI voice, speech, live typing, input, and file operation packages for NPU-equipped Copilot+ PCs",
            AppCategory::WindowsApps,
            "AI",
            "MicrosoftWindows.Voiess",
            vec![
                "MicrosoftWindows.Voiess",
                "MicrosoftWindows.Speion",
                "MicrosoftWindows.Livtop",
                "MicrosoftWindows.InpApp",
                "MicrosoftWindows.Filons",
            ],
            "",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "windows-app-edge",
            "Microsoft Edge",
            "Microsoft's web browser",
            AppCategory::WindowsApps,
            "Browsers",
            "Microsoft.MicrosoftEdge.Stable",
            vec!["Microsoft.MicrosoftEdge.Stable"],
            "",
            "",
            true,
            false,
            "XPFFTQ037JWMHS",
        ),
        app_item(
            "windows-app-onedrive",
            "OneDrive",
            "Microsoft's cloud storage service",
            AppCategory::WindowsApps,
            "System",
            "Microsoft.OneDriveSync",
            vec!["Microsoft.OneDriveSync"],
            "",
            "",
            true,
            false,
            "",
        ),
        app_item(
            "windows-app-onenote",
            "OneNote",
            "Microsoft note-taking app",
            AppCategory::WindowsApps,
            "Office",
            "Microsoft.Office.OneNote",
            vec!["Microsoft.Office.OneNote"],
            "",
            "",
            true,
            false,
            "XPFFZHVGQWWLHB",
        ),
    ]
}

fn get_capabilities() -> Vec<AppItem> {
    vec![
        app_item(
            "capability-internet-explorer",
            "Internet Explorer",
            "Legacy web browser",
            AppCategory::Capabilities,
            "Browser",
            "Browser.InternetExplorer",
            vec!["Browser.InternetExplorer"],
            "Browser.InternetExplorer",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "capability-powershell-ise",
            "PowerShell ISE",
            "PowerShell Integrated Scripting Environment",
            AppCategory::Capabilities,
            "Development",
            "Microsoft.Windows.PowerShell.ISE",
            vec!["Microsoft.Windows.PowerShell.ISE"],
            "Microsoft.Windows.PowerShell.ISE",
            "",
            true,
            false,
            "",
        ),
        app_item(
            "capability-quick-assist",
            "Quick Assist (Legacy)",
            "Remote assistance app",
            AppCategory::Capabilities,
            "System",
            "App.Support.QuickAssist",
            vec!["App.Support.QuickAssist"],
            "App.Support.QuickAssist",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "capability-steps-recorder",
            "Steps Recorder",
            "Screen recording tool",
            AppCategory::Capabilities,
            "Utilities",
            "App.StepsRecorder",
            vec!["App.StepsRecorder"],
            "App.StepsRecorder",
            "",
            true,
            false,
            "",
        ),
        app_item(
            "capability-windows-media-player",
            "Windows Media Player",
            "Classic media player",
            AppCategory::Capabilities,
            "Media",
            "Media.WindowsMediaPlayer",
            vec!["Media.WindowsMediaPlayer"],
            "Media.WindowsMediaPlayer",
            "",
            true,
            false,
            "",
        ),
        app_item(
            "capability-wordpad",
            "WordPad",
            "Rich text editor",
            AppCategory::Capabilities,
            "Productivity",
            "Microsoft.Windows.WordPad",
            vec!["Microsoft.Windows.WordPad"],
            "Microsoft.Windows.WordPad",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "capability-notepad",
            "Notepad (Legacy)",
            "Simple text editor",
            AppCategory::Capabilities,
            "Productivity",
            "Microsoft.Windows.Notepad",
            vec!["Microsoft.Windows.Notepad"],
            "Microsoft.Windows.Notepad",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "capability-paint-legacy",
            "Paint (Legacy)",
            "Classic Paint app",
            AppCategory::Capabilities,
            "Graphics",
            "Microsoft.Windows.MSPaint",
            vec!["Microsoft.Windows.MSPaint"],
            "Microsoft.Windows.MSPaint",
            "",
            false,
            false,
            "",
        ),
        app_item(
            "capability-openssh-client",
            "OpenSSH Client",
            "Secure Shell client for remote connections",
            AppCategory::Capabilities,
            "Networking",
            "OpenSSH.Client",
            vec!["OpenSSH.Client"],
            "OpenSSH.Client",
            "",
            true,
            false,
            "",
        ),
        app_item(
            "capability-openssh-server",
            "OpenSSH Server",
            "Secure Shell server for remote connections",
            AppCategory::Capabilities,
            "Networking",
            "OpenSSH.Server",
            vec!["OpenSSH.Server"],
            "OpenSSH.Server",
            "",
            true,
            false,
            "",
        ),
    ]
}

fn get_optional_features() -> Vec<AppItem> {
    vec![
        app_item(
            "feature-wsl",
            "Subsystem for Linux",
            "Allows running Linux binary executables natively on Windows",
            AppCategory::OptionalFeatures,
            "Development",
            "Microsoft-Windows-Subsystem-Linux",
            vec!["Microsoft-Windows-Subsystem-Linux"],
            "",
            "Microsoft-Windows-Subsystem-Linux",
            true,
            true,
            "",
        ),
        app_item(
            "feature-hyperv-platform",
            "Windows Hypervisor Platform",
            "Core virtualization platform without Hyper-V management tools",
            AppCategory::OptionalFeatures,
            "Virtualization",
            "Microsoft-Hyper-V-Hypervisor",
            vec!["Microsoft-Hyper-V-Hypervisor"],
            "",
            "Microsoft-Hyper-V-Hypervisor",
            true,
            true,
            "",
        ),
        app_item(
            "feature-hyperv",
            "Hyper-V",
            "Virtualization platform for running multiple operating systems",
            AppCategory::OptionalFeatures,
            "Virtualization",
            "Microsoft-Hyper-V-All",
            vec!["Microsoft-Hyper-V-All"],
            "",
            "Microsoft-Hyper-V-All",
            true,
            true,
            "",
        ),
        app_item(
            "feature-hyperv-tools",
            "Hyper-V Management Tools",
            "Tools for managing Hyper-V virtual machines",
            AppCategory::OptionalFeatures,
            "Virtualization",
            "Microsoft-Hyper-V-Tools-All",
            vec!["Microsoft-Hyper-V-Tools-All"],
            "",
            "Microsoft-Hyper-V-Tools-All",
            true,
            false,
            "",
        ),
        app_item(
            "feature-dotnet35",
            ".NET Framework 3.5",
            "Legacy .NET Framework for older applications",
            AppCategory::OptionalFeatures,
            "Development",
            "NetFx3",
            vec!["NetFx3"],
            "",
            "NetFx3",
            true,
            true,
            "",
        ),
        app_item(
            "feature-windows-sandbox",
            "Windows Sandbox",
            "Isolated desktop environment for running applications",
            AppCategory::OptionalFeatures,
            "Security",
            "Containers-DisposableClientVM",
            vec!["Containers-DisposableClientVM"],
            "",
            "Containers-DisposableClientVM",
            true,
            true,
            "",
        ),
        app_item(
            "feature-recall",
            "Recall",
            "Windows 11 feature that records user activity",
            AppCategory::OptionalFeatures,
            "System",
            "Recall",
            vec!["Recall"],
            "",
            "Recall",
            true,
            false,
            "",
        ),
    ]
}
