/// External software definitions for Downloads tab.

#[derive(Clone, Debug)]
pub struct DownloadApp {
    pub name: String,
    pub name_lc: String,
    pub description: String,
    pub description_lc: String,
    pub category: DownloadCategory,
    pub winget_ids: Vec<String>,
    pub winget_ids_lc: Vec<String>,
    pub website_url: String,
    pub website_url_lc: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum DownloadCategory {
    Browsers,
    DocumentViewers,
    MessagingEmailCalendar,
    OnlineStorageBackup,
    Multimedia,
    Imaging,
    CustomizationUtilities,
    Gaming,
    Compression,
    FileDiskManagement,
    RemoteAccess,
    OpticalDiscTools,
    OtherUtilities,
    PrivacySecurity,
    DevelopmentApps,
    RuntimesDependencies,
}

pub fn get_all_downloads() -> Vec<DownloadApp> {
    vec![
        app_ext(
            "Microsoft EdgeWebView",
            "WebView2 runtime for Windows applications",
            DownloadCategory::Browsers,
            vec!["Microsoft.EdgeWebView2Runtime".to_string()],
            "https://developer.microsoft.com/en-us/microsoft-edge/webview2/",
        ),
        app_ext(
            "Thorium",
            "Chromium-based browser with enhanced privacy features",
            DownloadCategory::Browsers,
            vec!["Alex313031.Thorium".to_string()],
            "https://thorium.rocks/",
        ),
        app_ext(
            "Mercury",
            "Compiler optimized, private Firefox fork",
            DownloadCategory::Browsers,
            vec!["Alex313031.Mercury".to_string()],
            "https://thorium.rocks/mercury",
        ),
        app_ext(
            "Mozilla Firefox",
            "Popular web browser known for privacy and customization",
            DownloadCategory::Browsers,
            vec!["Mozilla.Firefox".to_string()],
            "https://www.mozilla.org/firefox/",
        ),
        app_ext(
            "Google Chrome",
            "Google's web browser with sync and extension support",
            DownloadCategory::Browsers,
            vec!["Google.Chrome".to_string(), "Google.Chrome.EXE".to_string()],
            "https://www.google.com/chrome/",
        ),
        app_ext(
            "ungoogled-chromium",
            "Chromium-based browser with privacy enhancements",
            DownloadCategory::Browsers,
            vec!["Eloston.Ungoogled-Chromium".to_string()],
            "https://github.com/ungoogled-software/ungoogled-chromium-windows",
        ),
        app_ext(
            "Brave",
            "Privacy-focused browser with built-in ad blocking",
            DownloadCategory::Browsers,
            vec!["Brave.Brave".to_string()],
            "https://brave.com/",
        ),
        app_ext(
            "Opera",
            "Feature-rich web browser with built-in VPN and ad blocker",
            DownloadCategory::Browsers,
            vec!["Opera.Opera".to_string()],
            "https://www.opera.com/",
        ),
        app_ext(
            "Opera GX",
            "Gaming-oriented version of Opera with unique features",
            DownloadCategory::Browsers,
            vec!["Opera.OperaGX".to_string()],
            "https://www.opera.com/gx",
        ),
        app_ext(
            "Arc Browser",
            "Innovative browser with a focus on design and user experience",
            DownloadCategory::Browsers,
            vec!["TheBrowserCompany.Arc".to_string()],
            "https://arc.net/",
        ),
        app_ext(
            "Tor Browser",
            "Privacy-focused browser that routes traffic through the Tor network",
            DownloadCategory::Browsers,
            vec!["TorProject.TorBrowser".to_string()],
            "https://www.torproject.org/",
        ),
        app_ext(
            "Vivaldi",
            "Highly customizable browser with a focus on user control",
            DownloadCategory::Browsers,
            vec!["Vivaldi.Vivaldi".to_string()],
            "https://vivaldi.com/",
        ),
        app_ext(
            "Waterfox",
            "Firefox-based browser with a focus on privacy and customization",
            DownloadCategory::Browsers,
            vec!["Waterfox.Waterfox".to_string()],
            "https://www.waterfox.net/",
        ),
        app_ext(
            "Zen Browser",
            "Privacy-focused browser with built-in ad blocking",
            DownloadCategory::Browsers,
            vec!["Zen-Team.Zen-Browser".to_string()],
            "https://zen-browser.app/",
        ),
        app_ext(
            "Mullvad Browser",
            "Privacy-focused browser designed to minimize tracking and fingerprints",
            DownloadCategory::Browsers,
            vec!["MullvadVPN.MullvadBrowser".to_string()],
            "https://mullvad.net/en/browser",
        ),
        app_ext(
            "Pale Moon Browser",
            "Open Source, Goanna-based web browser focusing on efficiency and customization",
            DownloadCategory::Browsers,
            vec!["MoonchildProductions.PaleMoon".to_string()],
            "https://www.palemoon.org/",
        ),
        app_ext(
            "Maxthon",
            "Privacy focused browser with built-in ad blocking and VPN",
            DownloadCategory::Browsers,
            vec!["Maxthon.Maxthon".to_string()],
            "https://www.maxthon.com/",
        ),
        app_ext(
            "Ablaze Floorp",
            "Privacy focused browser with strong tracking protection",
            DownloadCategory::Browsers,
            vec!["Ablaze.Floorp".to_string()],
            "https://floorp.app/",
        ),
        app_ext(
            "DuckDuckGo",
            "Privacy-focused search engine with a browser extension",
            DownloadCategory::Browsers,
            vec!["DuckDuckGo.DesktopBrowser".to_string()],
            "https://duckduckgo.com/",
        ),
        app_ext(
            "LibreOffice",
            "Free and open-source office suite",
            DownloadCategory::DocumentViewers,
            vec!["TheDocumentFoundation.LibreOffice".to_string()],
            "https://www.libreoffice.org/",
        ),
        app_ext(
            "ONLYOFFICE Desktop Editors",
            "100% open-source free alternative to Microsoft Office",
            DownloadCategory::DocumentViewers,
            vec!["ONLYOFFICE.DesktopEditors".to_string()],
            "https://www.onlyoffice.com/",
        ),
        app_ext(
            "PDFgear",
            "Read, edit, convert, merge, and sign PDF files across devices, for completely free and without signing up.",
            DownloadCategory::DocumentViewers,
            vec!["PDFgear.PDFgear".to_string()],
            "https://www.pdfgear.com/",
        ),
        app_ext(
            "Foxit PDF Reader",
            "Lightweight PDF reader with advanced features",
            DownloadCategory::DocumentViewers,
            vec![],
            "https://www.foxit.com/pdf-reader/",
        ),
        app_ext(
            "SumatraPDF",
            "PDF, eBook (epub, mobi), comic book (cbz/cbr), DjVu, XPS, CHM, image viewer for Windows",
            DownloadCategory::DocumentViewers,
            vec!["SumatraPDF.SumatraPDF".to_string()],
            "https://www.sumatrapdfreader.org/",
        ),
        app_ext(
            "OpenOffice",
            "Discontinued open-source office suite. Active successor projects is LibreOffice",
            DownloadCategory::DocumentViewers,
            vec!["Apache.OpenOffice".to_string()],
            "https://www.openoffice.org/",
        ),
        app_ext(
            "Adobe Acrobat Reader DC",
            "PDF reader and editor",
            DownloadCategory::DocumentViewers,
            vec![],
            "https://www.adobe.com/acrobat/pdf-reader.html",
        ),
        app_ext(
            "Evernote",
            "Note-taking app",
            DownloadCategory::DocumentViewers,
            vec!["Evernote.Evernote".to_string()],
            "https://evernote.com/",
        ),
        app_ext(
            "CherryTree",
            "Hierarchical note taking application with rich text and syntax highlighting",
            DownloadCategory::DocumentViewers,
            vec!["Giuspen.Cherrytree".to_string()],
            "https://www.giuspen.net/cherrytree/",
        ),
        app_ext(
            "Okular",
            "Universal document viewer supporting PDF, eBook, and more",
            DownloadCategory::DocumentViewers,
            vec!["KDE.Okular".to_string(), "KDE.Okular.AppX".to_string()],
            "https://okular.kde.org/",
        ),
        app_ext(
            "PDF24 Creator",
            "Free PDF creator and converter",
            DownloadCategory::DocumentViewers,
            vec!["geeksoftwareGmbH.PDF24Creator".to_string()],
            "https://www.pdf24.org/",
        ),
        app_ext(
            "Telegram Desktop",
            "Instant messaging and voice calling app",
            DownloadCategory::MessagingEmailCalendar,
            vec!["Telegram.TelegramDesktop".to_string()],
            "https://telegram.org/",
        ),
        app_ext(
            "WhatsApp",
            "Instant messaging and voice calling app",
            DownloadCategory::MessagingEmailCalendar,
            vec![],
            "https://www.whatsapp.com/",
        ),
        app_ext(
            "Zoom Workplace",
            "Video conferencing and messaging platform",
            DownloadCategory::MessagingEmailCalendar,
            vec!["Zoom.Zoom".to_string()],
            "https://zoom.us/",
        ),
        app_ext(
            "Discord",
            "Voice, video and text communication service",
            DownloadCategory::MessagingEmailCalendar,
            vec!["Discord.Discord".to_string()],
            "https://discord.com/",
        ),
        app_ext(
            "Pidgin",
            "Multi-protocol instant messaging client",
            DownloadCategory::MessagingEmailCalendar,
            vec!["Pidgin.Pidgin".to_string()],
            "https://pidgin.im/",
        ),
        app_ext(
            "Mozilla Thunderbird",
            "Free email application",
            DownloadCategory::MessagingEmailCalendar,
            vec!["Mozilla.Thunderbird".to_string()],
            "https://www.thunderbird.net/",
        ),
        app_ext(
            "eM Client",
            "Email client with calendar, tasks, and chat",
            DownloadCategory::MessagingEmailCalendar,
            vec!["eMClient.eMClient".to_string()],
            "https://www.emclient.com/",
        ),
        app_ext(
            "Proton Mail",
            "Secure email service with end-to-end encryption",
            DownloadCategory::MessagingEmailCalendar,
            vec!["Proton.ProtonMail".to_string()],
            "https://proton.me/mail",
        ),
        app_ext(
            "Trillian",
            "Instant messaging application",
            DownloadCategory::MessagingEmailCalendar,
            vec!["CeruleanStudios.Trillian".to_string()],
            "https://www.trillian.im/",
        ),
        app_ext(
            "Google Drive",
            "Cloud storage and file synchronization service",
            DownloadCategory::OnlineStorageBackup,
            vec!["Google.GoogleDrive".to_string()],
            "https://www.google.com/drive/",
        ),
        app_ext(
            "Dropbox",
            "File hosting service that offers cloud storage, file synchronization, personal cloud",
            DownloadCategory::OnlineStorageBackup,
            vec!["Dropbox.Dropbox".to_string()],
            "https://www.dropbox.com/",
        ),
        app_ext(
            "SugarSync",
            "Automatically access and share your photos, videos, and files in any folder",
            DownloadCategory::OnlineStorageBackup,
            vec!["IPVanish.SugarSync".to_string()],
            "https://www.sugarsync.com/",
        ),
        app_ext(
            "Nextcloud",
            "Access, share and protect your files, calendars, contacts, communication & more at home and in your organization",
            DownloadCategory::OnlineStorageBackup,
            vec!["Nextcloud.NextcloudDesktop".to_string()],
            "https://nextcloud.com/",
        ),
        app_ext(
            "Proton Drive",
            "Secure cloud storage with end-to-end encryption",
            DownloadCategory::OnlineStorageBackup,
            vec!["Proton.ProtonDrive".to_string()],
            "https://proton.me/drive",
        ),
        app_ext(
            "FreeFileSync",
            "Open-source folder comparison and synchronization tool",
            DownloadCategory::OnlineStorageBackup,
            vec![],
            "https://freefilesync.org/",
        ),
        app_ext(
            "Hekasoft Backup & Restore",
            "The complete free solution for browser backup and management",
            DownloadCategory::OnlineStorageBackup,
            vec!["Hekasoft.Backup-Restore".to_string()],
            "https://hekasoft.com/hekasoft-backup-restore/",
        ),
        app_ext(
            "VLC media player",
            "Open-source multimedia player and framework",
            DownloadCategory::Multimedia,
            vec!["VideoLAN.VLC".to_string()],
            "https://www.videolan.org/vlc/",
        ),
        app_ext(
            "iTunes",
            "Media player and library",
            DownloadCategory::Multimedia,
            vec!["Apple.iTunes".to_string()],
            "https://www.apple.com/itunes/",
        ),
        app_ext(
            "AIMP",
            "Audio player with support for various formats",
            DownloadCategory::Multimedia,
            vec!["AIMP.AIMP".to_string()],
            "https://www.aimp.ru/",
        ),
        app_ext(
            "foobar2000",
            "Advanced audio player for Windows",
            DownloadCategory::Multimedia,
            vec!["PeterPawlowski.foobar2000".to_string()],
            "https://www.foobar2000.org/",
        ),
        app_ext(
            "MusicBee",
            "Music manager and player",
            DownloadCategory::Multimedia,
            vec![],
            "https://www.getmusicbee.com/",
        ),
        app_ext(
            "Audacity",
            "Audio editor and recorder",
            DownloadCategory::Multimedia,
            vec!["Audacity.Audacity".to_string()],
            "https://www.audacityteam.org/",
        ),
        app_ext(
            "GOM Player",
            "Media player for Windows",
            DownloadCategory::Multimedia,
            vec!["GOMLab.GOMPlayer".to_string()],
            "https://www.gomlab.com/",
        ),
        app_ext(
            "Spotify",
            "Music streaming service",
            DownloadCategory::Multimedia,
            vec!["Spotify.Spotify".to_string()],
            "https://www.spotify.com/",
        ),
        app_ext(
            "MediaMonkey",
            "Media manager and player",
            DownloadCategory::Multimedia,
            vec!["VentisMedia.MediaMonkey.5".to_string()],
            "https://www.mediamonkey.com/",
        ),
        app_ext(
            "HandBrake",
            "Open-source video transcoder",
            DownloadCategory::Multimedia,
            vec!["HandBrake.HandBrake".to_string()],
            "https://handbrake.fr/",
        ),
        app_ext(
            "OBS Studio",
            "Free and open source software for video recording and live streaming",
            DownloadCategory::Multimedia,
            vec!["OBSProject.OBSStudio".to_string()],
            "https://obsproject.com/",
        ),
        app_ext(
            "Streamlabs OBS",
            "Streaming software built on OBS with additional features for streamers",
            DownloadCategory::Multimedia,
            vec![],
            "https://streamlabs.com/",
        ),
        app_ext(
            "MPC-BE",
            "Media Player Classic - Black Edition",
            DownloadCategory::Multimedia,
            vec!["MPC-BE.MPC-BE".to_string()],
            "https://sourceforge.net/projects/mpcbe/",
        ),
        app_ext(
            "K-Lite Codec Pack (Mega)",
            "Collection of codecs and related tools",
            DownloadCategory::Multimedia,
            vec!["CodecGuide.K-LiteCodecPack.Mega".to_string()],
            "https://codecguide.com/",
        ),
        app_ext(
            "CapCut",
            "Video editor",
            DownloadCategory::Multimedia,
            vec!["ByteDance.CapCut".to_string()],
            "https://www.capcut.com/",
        ),
        app_ext(
            "PotPlayer64",
            "Comprehensive multimedia player for Windows",
            DownloadCategory::Multimedia,
            vec!["Daum.PotPlayer".to_string()],
            "https://potplayer.tv/",
        ),
        app_ext(
            "kdenlive",
            "Free and open-source video editing software",
            DownloadCategory::Multimedia,
            vec!["KDE.Kdenlive".to_string()],
            "https://kdenlive.org/",
        ),
        app_ext(
            "MediaInfo",
            "Technical information display tool for multimedia files",
            DownloadCategory::Multimedia,
            vec!["MediaArea.MediaInfo.GUI".to_string()],
            "https://mediaarea.net/en/MediaInfo",
        ),
        app_ext(
            "fre:ac - free audio converter",
            "Free audio converter and CD ripper",
            DownloadCategory::Multimedia,
            vec![],
            "https://www.freac.org/",
        ),
        app_ext(
            "SMPlayer",
            "Media Player with built-in codecs that can play virtually all video and audio formats",
            DownloadCategory::Multimedia,
            vec!["SMPlayer.SMPlayer".to_string()],
            "https://www.smplayer.info/",
        ),
        app_ext(
            "Shotcut",
            "Free, open-source, cross-platform video editor",
            DownloadCategory::Multimedia,
            vec!["Meltytech.Shotcut".to_string()],
            "https://www.shotcut.org/",
        ),
        app_ext(
            "LosslessCut",
            "Cross-platform FFmpeg GUI for fast, lossless video/audio trimming",
            DownloadCategory::Multimedia,
            vec!["ch.LosslessCut".to_string()],
            "https://github.com/mifi/lossless-cut",
        ),
        app_ext(
            "FxSound",
            "Audio enhancer for boosting sound quality on Windows",
            DownloadCategory::Multimedia,
            vec!["FxSound.FxSound".to_string()],
            "https://www.fxsound.com/",
        ),
        app_ext(
            "IrfanView64",
            "Fast and compact image viewer and converter",
            DownloadCategory::Imaging,
            vec!["IrfanSkiljan.IrfanView".to_string()],
            "https://www.irfanview.com/",
        ),
        app_ext(
            "Krita",
            "Digital painting and illustration software",
            DownloadCategory::Imaging,
            vec!["KDE.Krita".to_string()],
            "https://krita.org/",
        ),
        app_ext(
            "Blender",
            "3D creation suite",
            DownloadCategory::Imaging,
            vec!["BlenderFoundation.Blender".to_string()],
            "https://www.blender.org/",
        ),
        app_ext(
            "Paint.NET",
            "Image and photo editing software",
            DownloadCategory::Imaging,
            vec!["dotPDN.PaintDotNet".to_string()],
            "https://www.getpaint.net/",
        ),
        app_ext(
            "GIMP",
            "GNU Image Manipulation Program",
            DownloadCategory::Imaging,
            vec!["GIMP.GIMP.3".to_string()],
            "https://www.gimp.org/",
        ),
        app_ext(
            "XnViewMP",
            "Image viewer, browser and converter",
            DownloadCategory::Imaging,
            vec!["XnSoft.XnViewMP".to_string()],
            "https://www.xnview.com/en/xnviewmp/",
        ),
        app_ext(
            "XnView",
            "Image viewer, browser and converter (Classic Version)",
            DownloadCategory::Imaging,
            vec!["XnSoft.XnView.Classic".to_string()],
            "https://www.xnview.com/en/xnview/",
        ),
        app_ext(
            "Inkscape",
            "Vector graphics editor",
            DownloadCategory::Imaging,
            vec!["Inkscape.Inkscape".to_string()],
            "https://inkscape.org/",
        ),
        app_ext(
            "Greenshot",
            "Screenshot tool with annotation features",
            DownloadCategory::Imaging,
            vec!["Greenshot.Greenshot".to_string()],
            "https://getgreenshot.org/",
        ),
        app_ext(
            "ShareX",
            "Screen capture, file sharing and productivity tool",
            DownloadCategory::Imaging,
            vec!["ShareX.ShareX".to_string()],
            "https://getsharex.com/",
        ),
        app_ext(
            "Flameshot",
            "Powerful yet simple to use screenshot software",
            DownloadCategory::Imaging,
            vec!["Flameshot.Flameshot".to_string()],
            "https://flameshot.org/",
        ),
        app_ext(
            "FastStone Image Viewer",
            "Image browser, converter and editor",
            DownloadCategory::Imaging,
            vec!["FastStone.Viewer".to_string()],
            "https://www.faststone.org/",
        ),
        app_ext(
            "Nilesoft Shell",
            "Windows context menu customization tool",
            DownloadCategory::CustomizationUtilities,
            vec!["Nilesoft.Shell".to_string()],
            "https://nilesoft.org/",
        ),
        app_ext(
            "StartAllBack (Win 11)",
            "Windows 11 Start menu and taskbar customization",
            DownloadCategory::CustomizationUtilities,
            vec!["StartIsBack.StartAllBack".to_string()],
            "https://www.startallback.com/",
        ),
        app_ext(
            "StartIsBack++ (Win 10)",
            "Windows 10 Start menu and taskbar customization",
            DownloadCategory::CustomizationUtilities,
            vec!["StartIsBack.StartIsBack".to_string()],
            "https://www.startisback.com/",
        ),
        app_ext(
            "Open-Shell",
            "Classic style Start Menu for Windows",
            DownloadCategory::CustomizationUtilities,
            vec!["Open-Shell.Open-Shell-Menu".to_string()],
            "https://open-shell.github.io/Open-Shell-Menu/",
        ),
        app_ext(
            "Windhawk",
            "Customization platform for Windows",
            DownloadCategory::CustomizationUtilities,
            vec!["RamenSoftware.Windhawk".to_string()],
            "https://windhawk.net/",
        ),
        app_ext(
            "Lively Wallpaper",
            "Free and open-source animated desktop wallpaper application",
            DownloadCategory::CustomizationUtilities,
            vec!["rocksdanister.LivelyWallpaper".to_string()],
            "https://www.rocksdanister.com/lively/",
        ),
        app_ext(
            "Sucrose Wallpaper Engine",
            "Free and open-source animated desktop wallpaper application",
            DownloadCategory::CustomizationUtilities,
            vec!["Taiizor.SucroseWallpaperEngine".to_string()],
            "https://github.com/Taiizor/Sucrose",
        ),
        app_ext(
            "Rainmeter",
            "Desktop customization tool for Windows",
            DownloadCategory::CustomizationUtilities,
            vec!["Rainmeter.Rainmeter".to_string()],
            "https://www.rainmeter.net/",
        ),
        app_ext(
            "ExplorerPatcher",
            "Utility that enhances the Windows Explorer experience",
            DownloadCategory::CustomizationUtilities,
            vec!["valinet.ExplorerPatcher".to_string()],
            "https://github.com/valinet/ExplorerPatcher",
        ),
        app_ext(
            "John's Background Switcher",
            "Automatically changes your desktop wallpaper at regular intervals",
            DownloadCategory::CustomizationUtilities,
            vec!["johnsadventures.JohnsBackgroundSwitcher".to_string()],
            "https://johnsad.ventures/software/backgroundswitcher/",
        ),
        app_ext(
            "Microsoft PowerToys",
            "Set of utilities for power users to tune and streamline their Windows experience",
            DownloadCategory::CustomizationUtilities,
            vec!["Microsoft.PowerToys".to_string()],
            "https://github.com/microsoft/PowerToys",
        ),
        app_ext(
            "Nexus",
            "The advanced docking system for Windows",
            DownloadCategory::CustomizationUtilities,
            vec!["WinStep.Nexus".to_string()],
            "https://www.winstep.net/nexus.asp",
        ),
        app_ext(
            "AutoHotkey v2",
            "Free macro-creation and automation scripting language (v2, current)",
            DownloadCategory::CustomizationUtilities,
            vec!["AutoHotkey.AutoHotkey".to_string()],
            "https://www.autohotkey.com/",
        ),
        app_ext(
            "Steam",
            "Digital distribution platform for PC gaming",
            DownloadCategory::Gaming,
            vec!["Valve.Steam".to_string()],
            "https://store.steampowered.com/",
        ),
        app_ext(
            "Epic Games Launcher",
            "Digital distribution platform for PC gaming",
            DownloadCategory::Gaming,
            vec!["EpicGames.EpicGamesLauncher".to_string()],
            "https://www.epicgames.com/",
        ),
        app_ext(
            "7-Zip",
            "Open-source file archiver with a high compression ratio",
            DownloadCategory::Compression,
            vec!["7zip.7zip".to_string()],
            "https://www.7-zip.org/",
        ),
        app_ext(
            "WinRAR archiver",
            "File archiver with a high compression ratio",
            DownloadCategory::Compression,
            vec!["RARLab.WinRAR".to_string()],
            "https://www.win-rar.com/",
        ),
        app_ext(
            "PeaZip",
            "Free file archiver utility. Open and extract RAR, TAR, ZIP files and more",
            DownloadCategory::Compression,
            vec!["Giorgiotani.Peazip".to_string()],
            "https://peazip.github.io/",
        ),
        app_ext(
            "WinDirStat",
            "Disk usage statistics viewer and cleanup tool",
            DownloadCategory::FileDiskManagement,
            vec!["WinDirStat.WinDirStat".to_string()],
            "https://windirstat.net/",
        ),
        app_ext(
            "WizTree",
            "Disk space analyzer with extremely fast scanning",
            DownloadCategory::FileDiskManagement,
            vec!["AntibodySoftware.WizTree".to_string()],
            "https://www.diskanalyzer.com/",
        ),
        app_ext(
            "TreeSize Free",
            "Disk space manager",
            DownloadCategory::FileDiskManagement,
            vec!["JAMSoftware.TreeSize.Free".to_string()],
            "https://www.jam-software.com/treesize_free",
        ),
        app_ext(
            "Everything",
            "Locate files and folders by name instantly",
            DownloadCategory::FileDiskManagement,
            vec!["voidtools.Everything".to_string()],
            "https://www.voidtools.com/",
        ),
        app_ext(
            "TeraCopy",
            "Copy files faster and more securely",
            DownloadCategory::FileDiskManagement,
            vec!["CodeSector.TeraCopy".to_string()],
            "https://www.codesector.com/teracopy",
        ),
        app_ext(
            "File Converter",
            "Batch file converter for Windows",
            DownloadCategory::FileDiskManagement,
            vec!["AdrienAllard.FileConverter".to_string()],
            "https://file-converter.io/",
        ),
        app_ext(
            "Crystal Disk Info",
            "Hard drive health monitoring utility",
            DownloadCategory::FileDiskManagement,
            vec!["WsSolInfor.CrystalDiskInfo".to_string()],
            "https://crystalmark.info/en/software/crystaldiskinfo/",
        ),
        app_ext(
            "Bulk Rename Utility",
            "File renaming software for Windows",
            DownloadCategory::FileDiskManagement,
            vec!["TGRMNSoftware.BulkRenameUtility".to_string()],
            "https://www.bulkrenameutility.co.uk/",
        ),
        app_ext(
            "IObit Unlocker",
            "Tool to unlock files that are in use by other processes",
            DownloadCategory::FileDiskManagement,
            vec!["IObit.IObitUnlocker".to_string()],
            "https://www.iobit.com/en/iobit-unlocker.php",
        ),
        app_ext(
            "HiBit Uninstaller",
            "Completely Uninstall Stubborn Software, Windows Apps & Browser Extension",
            DownloadCategory::FileDiskManagement,
            vec!["HiBitSoftware.HiBitUninstaller".to_string()],
            "https://www.hibitsoft.ir/Uninstaller.html",
        ),
        app_ext(
            "SanDisk Dashboard",
            "Drive management tool for SanDisk SSDs and flash drives",
            DownloadCategory::FileDiskManagement,
            vec!["SanDisk.Dashboard".to_string()],
            "https://support-en.sandisk.com/app/products/downloads/softwaredownloads",
        ),
        app_ext(
            "Rufus",
            "Utility to create bootable USB flash drives",
            DownloadCategory::FileDiskManagement,
            vec!["Rufus.Rufus".to_string()],
            "https://rufus.ie/en/",
        ),
        app_ext(
            "Advanced Renamer",
            "Batch file renaming utility with advanced options",
            DownloadCategory::FileDiskManagement,
            vec!["HulubuluSoftware.AdvancedRenamer".to_string()],
            "https://www.advancedrenamer.com/",
        ),
        app_ext(
            "RustDesk",
            "Fast Open-Source Remote Access and Support Software",
            DownloadCategory::RemoteAccess,
            vec!["RustDesk.RustDesk".to_string()],
            "https://rustdesk.com/",
        ),
        app_ext(
            "AnyDesk",
            "Remote desktop software for remote access and support",
            DownloadCategory::RemoteAccess,
            vec!["AnyDesk.AnyDesk".to_string()],
            "https://anydesk.com/",
        ),
        app_ext(
            "TeamViewer",
            "Remote control, desktop sharing, online meetings, web conferencing and file transfer",
            DownloadCategory::RemoteAccess,
            vec!["TeamViewer.TeamViewer".to_string()],
            "https://www.teamviewer.com/",
        ),
        app_ext(
            "UltraViewer",
            "Helps you control your partner's computer to support them as if you were sitting in front of their screen",
            DownloadCategory::RemoteAccess,
            vec!["DucFabulous.UltraViewer".to_string()],
            "https://www.ultraviewer.net/",
        ),
        app_ext(
            "RealVNC Server",
            "Remote access software",
            DownloadCategory::RemoteAccess,
            vec!["RealVNC.VNCServer".to_string()],
            "https://www.realvnc.com/",
        ),
        app_ext(
            "RealVNC Viewer",
            "Remote access software",
            DownloadCategory::RemoteAccess,
            vec!["RealVNC.VNCViewer".to_string()],
            "https://www.realvnc.com/",
        ),
        app_ext(
            "Chrome Remote Desktop",
            "Remote access to your computer through Chrome browser",
            DownloadCategory::RemoteAccess,
            vec!["Google.ChromeRemoteDesktopHost".to_string()],
            "https://remotedesktop.google.com/",
        ),
        app_ext(
            "Parsec",
            "Remote desktop reimagined. Secure, flexible, effortless access to whatever you do, at any time, from wherever you go",
            DownloadCategory::RemoteAccess,
            vec!["Parsec.Parsec".to_string()],
            "https://parsec.app/",
        ),
        app_ext(
            "Parsec Virtual Display Driver",
            "Virtual display driver for Parsec Remote Desktop",
            DownloadCategory::RemoteAccess,
            vec!["Parsec.ParsecVDD".to_string()],
            "https://parsec.app/",
        ),
        app_ext(
            "Parsec Virtual USB Driver",
            "Virtual USB driver for Parsec Remote Desktop",
            DownloadCategory::RemoteAccess,
            vec!["Parsec.ParsecVUD".to_string()],
            "https://parsec.app/",
        ),
        app_ext(
            "InputLeap",
            "Open-source KVM software for sharing mouse and keyboard between computers",
            DownloadCategory::RemoteAccess,
            vec!["input-leap.input-leap".to_string()],
            "https://github.com/input-leap/input-leap",
        ),
        app_ext(
            "ImgBurn",
            "Lightweight CD / DVD / HD DVD / Blu-ray burning application",
            DownloadCategory::OpticalDiscTools,
            vec!["LIGHTNINGUK.ImgBurn".to_string()],
            "https://www.imgburn.com/",
        ),
        app_ext(
            "AnyBurn",
            "Lightweight CD/DVD/Blu-ray burning software",
            DownloadCategory::OpticalDiscTools,
            vec!["PowerSoftware.AnyBurn".to_string()],
            "http://www.anyburn.com/",
        ),
        app_ext(
            "CDBurnerXP",
            "Free CD/DVD/Blu-ray burning software",
            DownloadCategory::OpticalDiscTools,
            vec![],
            "https://cdburnerxp.se/",
        ),
        app_ext(
            "CCleaner",
            "System optimization and cleaning tool",
            DownloadCategory::OtherUtilities,
            vec!["Piriform.CCleaner".to_string()],
            "https://www.ccleaner.com/",
        ),
        app_ext(
            "Snappy Driver Installer Origin",
            "Driver installer and updater",
            DownloadCategory::OtherUtilities,
            vec!["GlennDelahoy.SnappyDriverInstallerOrigin".to_string()],
            "https://www.snappy-driver-installer.org/",
        ),
        app_ext(
            "Wise Disk Cleaner",
            "Free Disk Cleanup and Defragment Tool",
            DownloadCategory::OtherUtilities,
            vec!["WiseCleaner.WiseDiskCleaner".to_string()],
            "https://www.wisecleaner.com/wise-disk-cleaner.html",
        ),
        app_ext(
            "Wise Registry Cleaner",
            "Registry cleaning and optimization tool",
            DownloadCategory::OtherUtilities,
            vec!["WiseCleaner.WiseRegistryCleaner".to_string()],
            "https://www.wisecleaner.com/wise-registry-cleaner.html",
        ),
        app_ext(
            "UniGetUI",
            "Universal package manager interface supporting WinGet, Chocolatey, and more",
            DownloadCategory::OtherUtilities,
            vec!["MartiCliment.UniGetUI".to_string()],
            "https://www.marticliment.com/unigetui/",
        ),
        app_ext(
            "OpenRGB",
            "Open source RGB lighting control software",
            DownloadCategory::OtherUtilities,
            vec!["OpenRGB.OpenRGB".to_string()],
            "https://openrgb.org/",
        ),
        app_ext(
            "OpenAudible",
            "Audiobook manager and converter for Audible files",
            DownloadCategory::OtherUtilities,
            vec!["OpenAudible.OpenAudible".to_string()],
            "https://openaudible.org/",
        ),
        app_ext(
            "NAPS2",
            "Document scanning application with OCR support",
            DownloadCategory::OtherUtilities,
            vec!["Cyanfish.NAPS2".to_string()],
            "https://www.naps2.com/",
        ),
        app_ext(
            "IObit Uninstaller",
            "Completely Uninstall Unwanted Software, Windows Apps & Browser Plug-ins",
            DownloadCategory::OtherUtilities,
            vec!["IObit.Uninstaller".to_string()],
            "https://www.iobit.com/en/advanceduninstaller.php",
        ),
        app_ext(
            "Revo Uninstaller",
            "Revo Uninstaller helps you to uninstall software and remove unwanted programs easily.",
            DownloadCategory::OtherUtilities,
            vec!["RevoUninstaller.RevoUninstaller".to_string()],
            "https://www.revouninstaller.com/products/revo-uninstaller-free/",
        ),
        app_ext(
            "Malwarebytes",
            "Anti-malware software for Windows",
            DownloadCategory::PrivacySecurity,
            vec!["Malwarebytes.Malwarebytes".to_string()],
            "https://www.malwarebytes.com/",
        ),
        app_ext(
            "Malwarebytes AdwCleaner",
            "Adware removal tool for Windows",
            DownloadCategory::PrivacySecurity,
            vec!["Malwarebytes.AdwCleaner".to_string()],
            "https://www.malwarebytes.com/adwcleaner",
        ),
        app_ext(
            "Windows Firewall Control",
            "Malwarebytes Windows Firewall Control application",
            DownloadCategory::PrivacySecurity,
            vec!["BiniSoft.WindowsFirewallControl".to_string()],
            "https://www.binisoft.org/wfc",
        ),
        app_ext(
            "OnionShare",
            "Securely and anonymously share files, host websites, and chat via Tor network",
            DownloadCategory::PrivacySecurity,
            vec!["OnionShare.OnionShare".to_string()],
            "https://onionshare.org/",
        ),
        app_ext(
            "Sniffnet",
            "Network monitoring tool to analyze your internet traffic",
            DownloadCategory::PrivacySecurity,
            vec![],
            "https://sniffnet.net/",
        ),
        app_ext(
            "TeleGuard",
            "Secure messaging app with end-to-end encryption",
            DownloadCategory::PrivacySecurity,
            vec![],
            "https://teleguard.com/en",
        ),
        app_ext(
            "Python 3.13",
            "Python programming language",
            DownloadCategory::DevelopmentApps,
            vec!["Python.Python.3.13".to_string()],
            "https://www.python.org/",
        ),
        app_ext(
            "Notepad++",
            "Free source code editor and Notepad replacement",
            DownloadCategory::DevelopmentApps,
            vec!["Notepad++.Notepad++".to_string()],
            "https://notepad-plus-plus.org/",
        ),
        app_ext(
            "WinSCP",
            "Free SFTP, SCP, Amazon S3, WebDAV, and FTP client",
            DownloadCategory::DevelopmentApps,
            vec!["WinSCP.WinSCP".to_string()],
            "https://winscp.net/",
        ),
        app_ext(
            "PuTTY",
            "Free SSH and telnet client",
            DownloadCategory::DevelopmentApps,
            vec!["PuTTY.PuTTY".to_string()],
            "https://www.putty.org/",
        ),
        app_ext(
            "WinMerge",
            "Open source differencing and merging tool",
            DownloadCategory::DevelopmentApps,
            vec!["WinMerge.WinMerge".to_string()],
            "https://winmerge.org/",
        ),
        app_ext(
            "Eclipse IDE for Java",
            "Java IDE and development platform",
            DownloadCategory::DevelopmentApps,
            vec!["EclipseFoundation.Eclipse.Java".to_string()],
            "https://eclipseide.org/",
        ),
        app_ext(
            "Microsoft Visual Studio Code",
            "Code editor with support for development operations",
            DownloadCategory::DevelopmentApps,
            vec!["Microsoft.VisualStudioCode".to_string()],
            "https://code.visualstudio.com/",
        ),
        app_ext(
            "Git",
            "Distributed version control system",
            DownloadCategory::DevelopmentApps,
            vec!["Git.Git".to_string()],
            "https://git-scm.com/",
        ),
        app_ext(
            "GitHub Desktop",
            "GitHub desktop client",
            DownloadCategory::DevelopmentApps,
            vec!["GitHub.GitHubDesktop".to_string()],
            "https://desktop.github.com/",
        ),
        app_ext(
            "Microsoft .NET Runtime 3.1",
            ".NET Runtime 3.1 for running applications",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.DotNet.Runtime.3_1".to_string()],
            "https://dotnet.microsoft.com/",
        ),
        app_ext(
            "Microsoft .NET Runtime 5.0",
            ".NET Runtime 5.0 for running applications",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.DotNet.Runtime.5".to_string()],
            "https://dotnet.microsoft.com/",
        ),
        app_ext(
            "Microsoft .NET Runtime 6.0",
            ".NET Runtime 6.0 LTS for running applications",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.DotNet.Runtime.6".to_string()],
            "https://dotnet.microsoft.com/",
        ),
        app_ext(
            "Microsoft .NET Runtime 7.0",
            ".NET Runtime 7.0 for running applications",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.DotNet.Runtime.7".to_string()],
            "https://dotnet.microsoft.com/",
        ),
        app_ext(
            "Microsoft .NET Runtime 8.0",
            ".NET Runtime 8.0 LTS for running applications",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.DotNet.Runtime.8".to_string()],
            "https://dotnet.microsoft.com/",
        ),
        app_ext(
            ".NET Framework 4.8.1",
            ".NET Framework Developer Pack",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.DotNet.Framework.DeveloperPack_4".to_string()],
            "https://dotnet.microsoft.com/download/dotnet-framework",
        ),
        app_ext(
            "DirectX Runtime",
            "DirectX runtime components for running games and multimedia applications",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.DirectX".to_string()],
            "https://www.microsoft.com/en-us/download/details.aspx?id=35",
        ),
        app_ext(
            "Java Runtime Environment",
            "Java runtime environment for running Java applications",
            DownloadCategory::RuntimesDependencies,
            vec!["Oracle.JavaRuntimeEnvironment".to_string()],
            "https://www.oracle.com/java/technologies/downloads/",
        ),
        app_ext(
            "Visual C++ 2005 (x86)",
            "Visual C++ 2005 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2005.x86".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2005 (x64)",
            "Visual C++ 2005 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2005.x64".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2008 (x86)",
            "Visual C++ 2008 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2008.x86".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2008 (x64)",
            "Visual C++ 2008 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2008.x64".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2010 (x86)",
            "Visual C++ 2010 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2010.x86".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2010 (x64)",
            "Visual C++ 2010 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2010.x64".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2012 (x86)",
            "Visual C++ 2012 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2012.x86".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2012 (x64)",
            "Visual C++ 2012 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2012.x64".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2013 (x86)",
            "Visual C++ 2013 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2013.x86".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2013 (x64)",
            "Visual C++ 2013 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2013.x64".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2015-2022 (x86)",
            "Visual C++ 2015-2022 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2015+.x86".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Visual C++ 2015-2022 (x64)",
            "Visual C++ 2015-2022 runtime components",
            DownloadCategory::RuntimesDependencies,
            vec!["Microsoft.VCRedist.2015+.x64".to_string()],
            "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist",
        ),
        app_ext(
            "Tabby",
            "SSH terminal and connection manager",
            DownloadCategory::DevelopmentApps,
            vec!["Eugeny.Tabby".to_string()],
            "https://github.com/Eugeny/tabby",
        ),
        app_ext(
            "Riot Games Launcher",
            "Riot client launcher (manual login may be required)",
            DownloadCategory::Gaming,
            vec![],
            "https://www.riotgames.com/en",
        ),
        app_ext(
            "Helium Browser",
            "Privacy-focused Chromium browser",
            DownloadCategory::Browsers,
            vec!["ImputNet.Helium".to_string()],
            "https://github.com/imputnet/helium-windows",
        ),
        app_ext(
            "DataGrip",
            "JetBrains SQL IDE",
            DownloadCategory::DevelopmentApps,
            vec!["JetBrains.DataGrip".to_string()],
            "https://www.jetbrains.com/datagrip/download/?section=windows",
        ),
        app_ext(
            "Zed",
            "High-performance code editor",
            DownloadCategory::DevelopmentApps,
            vec!["ZedIndustries.Zed".to_string()],
            "https://zed.dev/download",
        ),
    ]
}

fn app_ext(
    name: &str,
    desc: &str,
    cat: DownloadCategory,
    winget_ids: Vec<String>,
    website_url: &str,
) -> DownloadApp {
    let winget_ids_lc: Vec<String> = winget_ids.iter().map(|s| s.to_ascii_lowercase()).collect();
    DownloadApp {
        name: name.to_string(),
        name_lc: name.to_ascii_lowercase(),
        description: desc.to_string(),
        description_lc: desc.to_ascii_lowercase(),
        category: cat,
        winget_ids,
        winget_ids_lc,
        website_url: website_url.to_string(),
        website_url_lc: website_url.to_ascii_lowercase(),
    }
}
